/**
*  @file
*  @copyright defined in go-seele/LICENSE
 */
package common

const (
	// HashLength the leghth of hash
	HashLength = 32
)

// Hash the hash value generated by sha-3
type Hash [HashLength]byte

// BytesToHash convert bytes to hash value
func BytesToHash(b []byte) Hash {
	var a Hash
	a.SetBytes(b)
	return a
}

// StringToHash string to hash
func StringToHash(s string) Hash {
	return BytesToHash([]byte(s))
}

// SetBytes sets the hash to the value of b. If b is larger than len(a) it will panic
func (a *Hash) SetBytes(b []byte) {
	copy(a[:], b)
}

// Bytes return its actual bits
func (a *Hash) Bytes() []byte {
	return a[:]
}

// String to string
func (a *Hash) String() string {
	return string(a[:])
}
